{
	"data": "ENC[AES256_GCM,data:Y8tpYGK1l74Xc0da5xz9/X1H+N7UhAEbohq/ymlXhxkd5wnwz2CwNGEvCTy5TW6M75luSnSNeKWaWfaUWIYnNweFDKZPP11+D8faHYMTD4qNANUzu3EtKKBreTxEqCKbMjm7w0FdPrLkb/W9UeZ9nogL6dErcVihdwbOEh88xPtgM+T1i1ZDXyzal1e0xrO6cKwhDjyl7Yzy7cl8zlOHEBXsiLQRMEN44Yl2BKe8auxcENctQM+I1WBQ1M9ppmf9v5XWsch3QHhY537dodDVBoAv2gndaRb3E+Cqe+Boy+Fgo/q669WCg49+E5RL4rm0tCKmpSdDp+cnmA7PNUFzliZlPnvOZn68Z0KZLyjnJA0jJBQzVgMGapJevQ2R2JtSPl7tTU+dH9+lZeJ8dhe/m80NW9hXtijZi/sJqM4WyAjUAmAB2ozeJ6OgncDvqcULuxT+7LlcN1RXn/SQjhglrTwmXr0voGxyQYif2rODblAxQUCB9lCAPrYWR5+8QrLG3kF1vjhxzUjmSbc=,iv:zZnSlbcGjpPbnDMudrnSgJPzSLT7/EsajEUcPfsQkOI=,tag:qC2ulWqzaMBTsVe/LQan5g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1wxfxdf2cjcuy3hmqvdkgswz5w08k245k6h8qewq35st8gqrued2q5wzd8c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYXg1bUF5U21uOVpIU2lH\nKzhzL2JtYUdEeWhMT1JMTE8yNVFKNlNxNTJvCjR4Vi9henFvRy9zS21sWmtEait6\nbWNaVUVBQXBobXZLeVJCY0FwWHpvOXMKLS0tIFE3b0VvQVdXU3MrUXhtbGxPTmM2\nWlRLMXUvSGhRanFqOERxVEw5WnowMk0KvYQVqksQzv+Hr5xKgkTXWbpdfhzVUkq4\nR/djGWkwPq1nFzx76eH9sn1dx7mlEAaMiffYxmEt2xNk3pW5XHiADQ==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age12svyxwc0vgvnahqhk57y0n5q9sag3ylmgmv3src6vgqm94yz04hqc3rzjz",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaGZqdGNwNjIxNDBSUlFX\ncFQ3eFMvd29RaFQ5VklibU9FSll5RklhRFhVCmlITnhNNXJnOTVtWmljNkFYSGxL\nM1FzRGVVZGhPekNoZ05Wb0xOSlk1Tm8KLS0tIFlBVFZaNUJjeWFxbGdnTGpvWWNu\ncUR4ZHNvRmJ6QkRvVVZtbTBMbEhjNjgKTGIL1v+90vg4twggSMSABt+2to68p2SQ\nLguFlzMO+POWgwNFmljs5Ia7t6T3RNLewXYMydyrGOGs1xG85+/kfQ==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1auth79lm39mvcvmknp0lfhtwx7ugrmtpwvt750pyfm2pj8844pas6peexx",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUTljM1YxcVl4WjVrNDJE\na1JtMVU0eWhtY3M5SlBsU29wdC9za0plWmg4CjhrOXA3ZmJSbjk3RmRaY2h1a0FC\nWk83eStkc2tsemc2UVlFK2tuSDdzT0EKLS0tIFo5bSs5RDB0T256UzBvalU3ZXRz\nVWx2TEVOeGg0L0prUVlvR1lXc2NSR1UKv3KQ0V787fvOD9xYZXJlpbcikXubEiP2\n/odUbq8QtgCIsRM9UdNcffFYcja45rrej0uxUTEi0KldPV32Z5aKmw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-11-28T02:50:59Z",
		"mac": "ENC[AES256_GCM,data:Nfb5wcHX5h1lgU10WuXf+SaL8dCoh6VxxPMVkIs01oL2KWfv/stPQrSeQbqU4MW+DDqKM7GUU26zsDLLi3EwX85TdqUG9f4qk8qBy0X+C/hY3PspUfHimJr059f2aechnm5H50J08/MmsKgwxzTgMuR/zluVUSm5pUbw3X8KAPc=,iv:GpgDMwVYfQkScLhbFX5f4fnqgxpmx3mKIWJfBvxA83Y=,tag:XrBjDGUAp6vZGUDoHd21dQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
